import React from "react";
import ReactDOM from "react-dom/client";
import theme from "./theme.jsx";
import { ChakraProvider } from "@chakra-ui/react";
import { Provider } from "./components/ui/provider";  // generated by snippet
import { ColorModeProvider } from "./components/ui/color-mode";
import { HashRouter } from "react-router-dom";
import App from "./App.jsx";
import "./index.css";
//import ErrorBoundary from "./ErrorBoundary.jsx";

ReactDOM.createRoot(document.getElementById("root")).render(
  <Provider>
    <ColorModeProvider>
      <ChakraProvider value={theme}>
        <HashRouter>
          <App />
        </HashRouter>
      </ChakraProvider>
    </ColorModeProvider>
  </Provider>

);
